"""Gerenciamento de wordlists e presets."""

import os

DEFAULT_WORDLIST = [
    "admin",
    "administrator",
    "login",
    "logon",
    "wp-admin",
    "panel",
    "painel",
    "config",
    "conf",
    "backup",
    "bak",
    "old",
    "db",
    "database",
    "sql",
    "setup",
    "dev",
    "development",
    "v1",
    "v2",
    "api",
    "test",
    "testing",
    "src",
    "git",
    "phpmyadmin",
    "server-status",
    "dashboard",
    "console",
    "shell",
    "uploads",
    "files",
    "images",
    "img",
    "assets",
    "css",
    "js",
    "javascript",
    "robots.txt",
    "info.php",
    "phpinfo.php",
    ".htaccess",
    ".env",
    "config.php",
    "README.md",
    "license.txt",
    "index.php.bak",
    "user.txt",
    "root.txt",
    ".htpasswd",
    ".git",
    ".svn",
    ".ssh",
    "cgi-bin",
    "server-info",
    "logs",
    "error_log",
    "includes",
    "inc",
    "lib",
    "library",
    "vendor",
    "node_modules",
    "system",
    "core",
    "bin",
    "etc",
    "var",
    "tmp",
    "admin/auth",
    "admin/config",
    "admin/db",
    "private",
    "secret",
    "secure",
    "restricted",
    "auth",
    "users",
    "accounts",
    "setup.php",
    "install.php",
    "status.php",
    "mysql",
    "db_backup",
    "dump.sql",
    "database.sql",
]


def load_wordlist(path: str) -> list:
    """Lê uma wordlist de arquivo; retorna lista de linhas não vazias e sem espaços."""
    if not path or not os.path.exists(path):
        return []
    with open(path, "r", encoding="utf-8") as f:
        return [line.strip() for line in f.readlines() if line.strip()]

